name       : opencolorio
version    : 1.1.1
release    : 4
source     :
    - https://github.com/AcademySoftwareFoundation/OpenColorIO/archive/v1.1.1.tar.gz : c9b5b9def907e1dafb29e37336b702fff22cc6306d445a13b1621b8a754c14c8
homepage   : https://opencolorio.org/
license    :
    - BSD-3-Clause
    - BSD-4-Clause
    - ZLib
component  : multimedia.library
summary    : A color management framework for visual effects and animation
description: |
    OpenColorIO (OCIO) is a complete color management solution geared towards motion picture production with an emphasis on visual effects and computer animation. OCIO provides a straightforward and consistent user experience across all supporting applications while allowing for sophisticated back-end configuration options suitable for high-end production usage. OCIO is compatible with the Academy Color Encoding Specification (ACES) and is LUT-format agnostic, supporting many popular formats.
builddeps  :
    - pkgconfig(lcms2)
    - pkgconfig(python3)
    - pkgconfig(tinyxml)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - pybind11
setup      : |
    %patch -p1 < $pkgfiles/yaml-cpp-visibility-from-hidden-to-default.patch
    %patch -p1 < $pkgfiles/install-CMake-modules-in-usr-lib-cmake.patch
    %patch -p1 < $pkgfiles/CMake-disable-Werror.patch

    %cmake_ninja \
        -DOCIO_BUILD_STATIC=OFF \
        -DLIB_SUFFIX=64 \
        -DUSE_EXTERNAL_YAML=ON \
        -DUSE_EXTERNAL_LCMS=ON \
        -DUSE_EXTERNAL_TINYXML=ON \
        -DPYTHON=python3
build      : |
    %ninja_build
install    : |
    %ninja_install
