name       : opencolorio
version    : 2.0.2
release    : 7
source     :
    - https://github.com/AcademySoftwareFoundation/OpenColorIO/archive/refs/tags/v2.0.1.tar.gz : ff1397b4516fdecd75096d5b575d6a23771d0c876bbcfc7beb5a82af37adcdf9
    - git|https://github.com/imageworks/pystring : 281419de2f91f9e0f2df6acddfea3b06a43436be
homepage   : https://opencolorio.org/
license    :
    - BSD-3-Clause
    - BSD-4-Clause
    - ZLib
component  : multimedia.library
summary    : A color management framework for visual effects and animation
description: |
    OpenColorIO (OCIO) is a complete color management solution geared towards motion picture production with an emphasis on visual effects and computer animation. OCIO provides a straightforward and consistent user experience across all supporting applications while allowing for sophisticated back-end configuration options suitable for high-end production usage. OCIO is compatible with the Academy Color Encoding Specification (ACES) and is LUT-format agnostic, supporting many popular formats.
builddeps  :
    - pkgconfig(Imath)
    - pkgconfig(expat)
    - pkgconfig(glew)
    - pkgconfig(glut)
    - pkgconfig(lcms2)
    - pkgconfig(python3)
    - pkgconfig(yaml-cpp)
    - libboost-devel
    - pybind11
setup      : |
    %patch -p1 --binary < $pkgfiles/Imath-instead-of-Half.patch
    %patch -p1 < $pkgfiles/OpenColorIOConfig-generation.patch

    cp -r $sources/pystring.git src/pystring
    pushd src/pystring
    x86_64-solus-linux-g++ $CXXFLAGS -o pystring.cpp.o -c pystring.cpp
    ar rcs libpystring.a pystring.cpp.o
    popd

    %cmake_ninja \
        -DOCIO_BUILD_STATIC=OFF \
        -DLIB_SUFFIX=64 \
        -Dpystring_LIBRARY=$workdir/src/pystring/libpystring.a \
        -Dpystring_INCLUDE_DIR=$workdir/src/pystring
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
