name       : opencolorio
version    : 1.0.9
release    : 3
source     :
    - https://github.com/imageworks/OpenColorIO/archive/v1.0.9.tar.gz : 27c81e691c15753cd2b560c2ca4bd5679a60c2350eedd43c99d44ca25d65ea7f
license    : 
    - BSD-3-Clause
    - ZLib
    - BSD-4-Clause
clang      : no
summary    : A color management framework for visual effects and animation.
description: |
    A color management framework for visual effects and animation.
builddeps  :
    - pkgconfig(lcms2)
    - g++
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
